package duan.UI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.sun.java.swing.plaf.windows.WindowsScrollBarUI;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;
import javax.swing.SwingConstants;

/**
 *
 * @author anhdu
 */
public class CanHoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CanHoJPanel
     */
    public CanHoJPanel() {
        initComponents();
        test();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcTang = new java.awt.Choice();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlCanHo = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1040, 660));
        setMinimumSize(new java.awt.Dimension(1040, 660));
        setPreferredSize(new java.awt.Dimension(1040, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(1040, 127));
        jPanel1.setMinimumSize(new java.awt.Dimension(1040, 127));
        jPanel1.setPreferredSize(new java.awt.Dimension(1040, 127));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(0, 153, 153));
        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setToolTipText("Tìm Phòng");
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Search.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TẦNG");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, 30));

        jcTang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcTang.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jcTang.setMaximumSize(new java.awt.Dimension(28, 25));
        jcTang.setName(""); // NOI18N
        jPanel1.add(jcTang, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 180, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        pnlCanHo.setBackground(new java.awt.Color(255, 255, 255));
        pnlCanHo.setMaximumSize(new java.awt.Dimension(1014, 541));
        pnlCanHo.setMinimumSize(new java.awt.Dimension(1014, 541));
        pnlCanHo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 6, 6));
        jScrollPane2.setViewportView(pnlCanHo);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1040, 540));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private java.awt.Choice jcTang;
    private javax.swing.JPanel pnlCanHo;
    // End of variables declaration//GEN-END:variables

    private void test() {
        int a = 25;

        for (int i = 0; i < a; i++) {
            JButton canho = new JButton();
            canho.setPreferredSize(new Dimension(245, 200));
            canho.setBackground(new Color(121, 196, 71));
            while (a % 3 != 0) {
                a++;
            }

            canho.setCursor(new Cursor(Cursor.HAND_CURSOR));
            canho.setPreferredSize(new Dimension(245, 195));
            canho.setIcon(new ImageIcon(this.getClass().getResource("/duan/Logo/LogoMain.png")));
            String noidung = "<html> <style>body{\n"
                    + "    text-align: center;\n"
                    + "    font-family: 'Tahoma';\n"
                    + "    color: white;\n"
                    + "}</style>";
            noidung += "<b><font size=5> 101 </b></font>";
            canho.setText(noidung);
            canho.setHorizontalAlignment(SwingConstants.CENTER);

            pnlCanHo.add(canho);
            pnlCanHo.setPreferredSize(new Dimension(1000, 155 * (a / 3)));
            jScrollPane2.setPreferredSize(new Dimension(1014, 500));
            jScrollPane2.getVerticalScrollBar().setUnitIncrement(20);
            jScrollPane2.setViewportView(pnlCanHo);
        }

        /* Neu so luong le thi lay so luong / 4. roi cong 1*/
    }
}
