package duan.UI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Nhom 6
 */
public class CanHoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CanHoJPanel
     */
    public CanHoJPanel() {
        initComponents();
        test();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        jPanel1 = new javax.swing.JPanel();
        txt_TimKiem = new javax.swing.JTextField();
        lblTimKiem = new javax.swing.JLabel();
        lblTang = new javax.swing.JLabel();
        cbo_Tang = new javax.swing.JComboBox<>();
        sclCanHo = new javax.swing.JScrollPane();
        pnlCanHo = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1040, 660));
        setMinimumSize(new java.awt.Dimension(1040, 660));
        setPreferredSize(new java.awt.Dimension(1040, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(1040, 127));
        jPanel1.setMinimumSize(new java.awt.Dimension(1040, 127));
        jPanel1.setPreferredSize(new java.awt.Dimension(1040, 127));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_TimKiem.setBackground(new java.awt.Color(0, 153, 153));
        txt_TimKiem.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        txt_TimKiem.setForeground(new java.awt.Color(255, 255, 255));
        txt_TimKiem.setToolTipText("Tìm Phòng");
        txt_TimKiem.setBorder(null);
        jPanel1.add(txt_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 270, 40));

        lblTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Search.png"))); // NOI18N
        jPanel1.add(lblTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        lblTang.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTang.setForeground(new java.awt.Color(255, 255, 255));
        lblTang.setText("TẦNG");
        jPanel1.add(lblTang, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, 30));

        cbo_Tang.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cbo_Tang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tầng 1", "Tầng 2", "Tầng 3", "Tầng 4", "Tầng 5", "Tầng 6" }));
        cbo_Tang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cbo_Tang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbo_Tang.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cbo_Tang.setMaximumSize(new java.awt.Dimension(87, 26));
        jPanel1.add(cbo_Tang, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 240, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        pnlCanHo.setBackground(new java.awt.Color(255, 255, 255));
        pnlCanHo.setMaximumSize(new java.awt.Dimension(1014, 541));
        pnlCanHo.setMinimumSize(new java.awt.Dimension(1014, 541));
        pnlCanHo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 6, 6));
        sclCanHo.setViewportView(pnlCanHo);

        add(sclCanHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1040, 540));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_Tang;
    private java.awt.Choice choice1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTang;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JPanel pnlCanHo;
    private javax.swing.JScrollPane sclCanHo;
    private javax.swing.JTextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables

    
    private void test() {
        int a = 52;
        
        for (int i = 0; i < a; i++) {
            ThongTinCanHo ttch = new ThongTinCanHo((i+1));
            JLabel canho = new JLabel();
            canho.setPreferredSize(new Dimension(245, 200));
            //o.setBackground(new Color(121, 196, 71));

            canho.setForeground(new Color(121, 196, 71));
            canho.setCursor(new Cursor(Cursor.HAND_CURSOR));
            canho.setBackground(new Color(121, 196, 71));
            canho.setPreferredSize(new Dimension(245, 195));
            canho.setHorizontalAlignment((int) LEFT_ALIGNMENT);
            canho.setIcon(new ImageIcon(this.getClass().getResource("/duan/Logo/LogoMain.png")));
            String noidung = "<html> <style>body{\n"
                    + "    text-align: center;\n"
                    + "    font-family: 'Tahoma';\n"
                    + "    color: white;\n"
                    + "}</style>";
            noidung += "<b><font size=5> Phòng " + (i + 1) + " </b></font>";
            canho.setText(noidung);
            canho.setHorizontalAlignment(SwingConstants.CENTER);
            canho.setOpaque(true);
            canho.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    ttch.setVisible(true);
                }
                
            });
            pnlCanHo.add(canho);
            if (a % 4 != 0) {
                pnlCanHo.setPreferredSize(new Dimension(1000, 200 * (a / 4 + 1)));
                
            } else {
                pnlCanHo.setPreferredSize(new Dimension(1000, 200 * (a / 4)));
                
            }
            
        }
        sclCanHo.setPreferredSize(new Dimension(1014, 500));
        sclCanHo.getVerticalScrollBar().setUnitIncrement(20);
        sclCanHo.setViewportView(pnlCanHo);
        
    }
}
