/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duan.UI;

/**
 *
 * @author anhdu
 */
public class DichVuPhongJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DichVu_HoaDonJPanel
     */
    public DichVuPhongJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_BangDichVu = new javax.swing.JTable();
        jpn_TongDichVu = new javax.swing.JPanel();
        lbl_CanHo = new javax.swing.JLabel();
        txt_CanHo = new javax.swing.JTextField();
        lbl_TienDVCoBan = new javax.swing.JLabel();
        lbl_TienGuiXe = new javax.swing.JLabel();
        txt_TienDVCoBan = new javax.swing.JTextField();
        lbl_GiaTienGuiXe = new javax.swing.JLabel();
        jpn_SoLuongXe = new javax.swing.JPanel();
        lbl_XeDap = new javax.swing.JLabel();
        lbl_XeMay = new javax.swing.JLabel();
        lbl_XeHoi = new javax.swing.JLabel();
        txt_XeDap = new javax.swing.JTextField();
        txt_XeMay = new javax.swing.JTextField();
        txt_XeHoi = new javax.swing.JTextField();
        jpn_NhapSLXe = new javax.swing.JPanel();
        lbl_Nhap = new javax.swing.JLabel();
        jpn_TruyVan = new javax.swing.JPanel();
        jpn_NutTruyVan = new javax.swing.JPanel();
        lbl_TruyVan = new javax.swing.JLabel();
        cbo_Thang = new javax.swing.JComboBox<>();
        lbl_Thang = new javax.swing.JLabel();
        cbo_Nam = new javax.swing.JComboBox<>();
        lbl_Nam = new javax.swing.JLabel();
        jpn_NhapDVPhong = new javax.swing.JPanel();
        lbl_NhapDVPhong = new javax.swing.JLabel();
        jpn_TaoHDThang = new javax.swing.JPanel();
        lbl_TaoHDThang = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1040, 660));
        setMinimumSize(new java.awt.Dimension(1040, 660));
        setPreferredSize(new java.awt.Dimension(1040, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_BangDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Căn Hộ", "Tiền Dịch Vụ Cơ Bản", "Tiền Gửi Xe", "Tổng Tiền"
            }
        ));
        jScrollPane1.setViewportView(tbl_BangDichVu);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 276, 1016, 310));

        jpn_TongDichVu.setBackground(new java.awt.Color(255, 255, 255));
        jpn_TongDichVu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jpn_TongDichVu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_CanHo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_CanHo.setText("Căn Hộ");
        jpn_TongDichVu.add(lbl_CanHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        txt_CanHo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpn_TongDichVu.add(txt_CanHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 153, -1));

        lbl_TienDVCoBan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TienDVCoBan.setText("Tiền Dịch Vụ Cơ Bản");
        jpn_TongDichVu.add(lbl_TienDVCoBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lbl_TienGuiXe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TienGuiXe.setText("Tiền Gửi Xe");
        jpn_TongDichVu.add(lbl_TienGuiXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        txt_TienDVCoBan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpn_TongDichVu.add(txt_TienDVCoBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 153, -1));

        lbl_GiaTienGuiXe.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_GiaTienGuiXe.setForeground(new java.awt.Color(255, 0, 0));
        lbl_GiaTienGuiXe.setText("200,000");
        jpn_TongDichVu.add(lbl_GiaTienGuiXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jpn_SoLuongXe.setBackground(new java.awt.Color(255, 255, 255));
        jpn_SoLuongXe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Số Lượng Xe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jpn_SoLuongXe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_XeDap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_XeDap.setText("Xe Đạp");
        jpn_SoLuongXe.add(lbl_XeDap, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 32, -1, -1));

        lbl_XeMay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_XeMay.setText("Xe Máy");
        jpn_SoLuongXe.add(lbl_XeMay, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 80, -1, -1));

        lbl_XeHoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_XeHoi.setText("Xe Hơi");
        jpn_SoLuongXe.add(lbl_XeHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 134, -1, -1));
        jpn_SoLuongXe.add(txt_XeDap, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 100, -1));
        jpn_SoLuongXe.add(txt_XeMay, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 100, -1));
        jpn_SoLuongXe.add(txt_XeHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 100, -1));

        jpn_NhapSLXe.setBackground(new java.awt.Color(153, 204, 0));
        jpn_NhapSLXe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpn_NhapSLXe.setMaximumSize(new java.awt.Dimension(99, 36));
        jpn_NhapSLXe.setMinimumSize(new java.awt.Dimension(99, 36));

        lbl_Nhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Nhap.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Wite.png"))); // NOI18N
        lbl_Nhap.setText("Nhập ");

        javax.swing.GroupLayout jpn_NhapSLXeLayout = new javax.swing.GroupLayout(jpn_NhapSLXe);
        jpn_NhapSLXe.setLayout(jpn_NhapSLXeLayout);
        jpn_NhapSLXeLayout.setHorizontalGroup(
            jpn_NhapSLXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_NhapSLXeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Nhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn_NhapSLXeLayout.setVerticalGroup(
            jpn_NhapSLXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Nhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jpn_SoLuongXe.add(jpn_NhapSLXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jpn_TongDichVu.add(jpn_SoLuongXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 230, 230));

        jpn_TruyVan.setBackground(new java.awt.Color(255, 255, 255));
        jpn_TruyVan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Truy Vấn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N

        jpn_NutTruyVan.setBackground(new java.awt.Color(255, 102, 102));
        jpn_NutTruyVan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_TruyVan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TruyVan.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TruyVan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Search_25px.png"))); // NOI18N
        lbl_TruyVan.setText("Truy Vấn");

        javax.swing.GroupLayout jpn_NutTruyVanLayout = new javax.swing.GroupLayout(jpn_NutTruyVan);
        jpn_NutTruyVan.setLayout(jpn_NutTruyVanLayout);
        jpn_NutTruyVanLayout.setHorizontalGroup(
            jpn_NutTruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_NutTruyVanLayout.createSequentialGroup()
                .addComponent(lbl_TruyVan, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpn_NutTruyVanLayout.setVerticalGroup(
            jpn_NutTruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_NutTruyVanLayout.createSequentialGroup()
                .addComponent(lbl_TruyVan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        cbo_Thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_Thang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Thang.setText("Tháng");

        cbo_Nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_Nam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Nam.setText("Năm");

        javax.swing.GroupLayout jpn_TruyVanLayout = new javax.swing.GroupLayout(jpn_TruyVan);
        jpn_TruyVan.setLayout(jpn_TruyVanLayout);
        jpn_TruyVanLayout.setHorizontalGroup(
            jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_TruyVanLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_TruyVanLayout.createSequentialGroup()
                        .addComponent(lbl_Thang)
                        .addGap(18, 18, 18)
                        .addComponent(cbo_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_TruyVanLayout.createSequentialGroup()
                        .addComponent(lbl_Nam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpn_NutTruyVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jpn_TruyVanLayout.setVerticalGroup(
            jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_TruyVanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Thang)
                    .addComponent(cbo_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Nam))
                .addGap(38, 38, 38)
                .addComponent(jpn_NutTruyVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpn_TongDichVu.add(jpn_TruyVan, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 240, 230));

        jpn_NhapDVPhong.setBackground(new java.awt.Color(153, 204, 0));
        jpn_NhapDVPhong.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpn_NhapDVPhong.setMaximumSize(new java.awt.Dimension(99, 36));
        jpn_NhapDVPhong.setMinimumSize(new java.awt.Dimension(99, 36));

        lbl_NhapDVPhong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_NhapDVPhong.setForeground(new java.awt.Color(255, 255, 255));
        lbl_NhapDVPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Wite.png"))); // NOI18N
        lbl_NhapDVPhong.setText("Nhập ");

        javax.swing.GroupLayout jpn_NhapDVPhongLayout = new javax.swing.GroupLayout(jpn_NhapDVPhong);
        jpn_NhapDVPhong.setLayout(jpn_NhapDVPhongLayout);
        jpn_NhapDVPhongLayout.setHorizontalGroup(
            jpn_NhapDVPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_NhapDVPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_NhapDVPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn_NhapDVPhongLayout.setVerticalGroup(
            jpn_NhapDVPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_NhapDVPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jpn_TongDichVu.add(jpn_NhapDVPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jpn_TaoHDThang.setBackground(new java.awt.Color(153, 204, 0));
        jpn_TaoHDThang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_TaoHDThang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TaoHDThang.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TaoHDThang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/New.png"))); // NOI18N
        lbl_TaoHDThang.setText("Tạo Hóa Đơn Tháng");

        javax.swing.GroupLayout jpn_TaoHDThangLayout = new javax.swing.GroupLayout(jpn_TaoHDThang);
        jpn_TaoHDThang.setLayout(jpn_TaoHDThangLayout);
        jpn_TaoHDThangLayout.setHorizontalGroup(
            jpn_TaoHDThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_TaoHDThangLayout.createSequentialGroup()
                .addComponent(lbl_TaoHDThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpn_TaoHDThangLayout.setVerticalGroup(
            jpn_TaoHDThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TaoHDThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpn_TongDichVu.add(jpn_TaoHDThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        add(jpn_TongDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 260));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_Nam;
    private javax.swing.JComboBox<String> cbo_Thang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpn_NhapDVPhong;
    private javax.swing.JPanel jpn_NhapSLXe;
    private javax.swing.JPanel jpn_NutTruyVan;
    private javax.swing.JPanel jpn_SoLuongXe;
    private javax.swing.JPanel jpn_TaoHDThang;
    private javax.swing.JPanel jpn_TongDichVu;
    private javax.swing.JPanel jpn_TruyVan;
    private javax.swing.JLabel lbl_CanHo;
    private javax.swing.JLabel lbl_GiaTienGuiXe;
    private javax.swing.JLabel lbl_Nam;
    private javax.swing.JLabel lbl_Nhap;
    private javax.swing.JLabel lbl_NhapDVPhong;
    private javax.swing.JLabel lbl_TaoHDThang;
    private javax.swing.JLabel lbl_Thang;
    private javax.swing.JLabel lbl_TienDVCoBan;
    private javax.swing.JLabel lbl_TienGuiXe;
    private javax.swing.JLabel lbl_TruyVan;
    private javax.swing.JLabel lbl_XeDap;
    private javax.swing.JLabel lbl_XeHoi;
    private javax.swing.JLabel lbl_XeMay;
    private javax.swing.JTable tbl_BangDichVu;
    private javax.swing.JTextField txt_CanHo;
    private javax.swing.JTextField txt_TienDVCoBan;
    private javax.swing.JTextField txt_XeDap;
    private javax.swing.JTextField txt_XeHoi;
    private javax.swing.JTextField txt_XeMay;
    // End of variables declaration//GEN-END:variables
}
