/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duan.UI;

/**
 *
 * @author anhdu
 */
public class InternetJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DichVu_HoaDonJPanel
     */
    public InternetJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbl_BangInternet = new javax.swing.JScrollPane();
        tbl_ChiTietInternet = new javax.swing.JTable();
        jpn_TacVu = new javax.swing.JPanel();
        lbl_CanHo = new javax.swing.JLabel();
        lbl_TienInternet = new javax.swing.JLabel();
        jpn_TruyVan = new javax.swing.JPanel();
        jpn_nutTruyVan = new javax.swing.JPanel();
        lbl_TruyVan = new javax.swing.JLabel();
        cbo_Nam = new javax.swing.JComboBox<>();
        lbl_Nam = new javax.swing.JLabel();
        lbl_Thang = new javax.swing.JLabel();
        cbo_Thang = new javax.swing.JComboBox<>();
        txt_CanHo = new javax.swing.JTextField();
        txt_TienInternet = new javax.swing.JTextField();
        jpn_Sua = new javax.swing.JPanel();
        lbl_Sua = new javax.swing.JLabel();
        jpn_Nhap = new javax.swing.JPanel();
        lbl_Nhap = new javax.swing.JLabel();
        jpn_TaoHDThang = new javax.swing.JPanel();
        lbl_TaoHDThang = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1040, 660));
        setMinimumSize(new java.awt.Dimension(1040, 660));
        setPreferredSize(new java.awt.Dimension(1040, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_ChiTietInternet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Căn Hộ", "Tiền Internet"
            }
        ));
        tbl_BangInternet.setViewportView(tbl_ChiTietInternet);

        add(tbl_BangInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 226, 1016, 356));

        jpn_TacVu.setBackground(new java.awt.Color(255, 255, 255));
        jpn_TacVu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        lbl_CanHo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_CanHo.setText("Căn Hộ");

        lbl_TienInternet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TienInternet.setText("Tiền Internet");

        jpn_TruyVan.setBackground(new java.awt.Color(255, 255, 255));
        jpn_TruyVan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Truy Vấn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N

        jpn_nutTruyVan.setBackground(new java.awt.Color(255, 102, 102));
        jpn_nutTruyVan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_TruyVan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TruyVan.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TruyVan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Search.png"))); // NOI18N
        lbl_TruyVan.setText("Truy Vấn");

        javax.swing.GroupLayout jpn_nutTruyVanLayout = new javax.swing.GroupLayout(jpn_nutTruyVan);
        jpn_nutTruyVan.setLayout(jpn_nutTruyVanLayout);
        jpn_nutTruyVanLayout.setHorizontalGroup(
            jpn_nutTruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_nutTruyVanLayout.createSequentialGroup()
                .addComponent(lbl_TruyVan, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpn_nutTruyVanLayout.setVerticalGroup(
            jpn_nutTruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TruyVan, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        cbo_Nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_NamActionPerformed(evt);
            }
        });

        lbl_Nam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Nam.setText("Năm");

        lbl_Thang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Thang.setText("Tháng");

        cbo_Thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jpn_TruyVanLayout = new javax.swing.GroupLayout(jpn_TruyVan);
        jpn_TruyVan.setLayout(jpn_TruyVanLayout);
        jpn_TruyVanLayout.setHorizontalGroup(
            jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_TruyVanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Thang)
                    .addComponent(lbl_Nam))
                .addGap(18, 18, 18)
                .addGroup(jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbo_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpn_nutTruyVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn_TruyVanLayout.setVerticalGroup(
            jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_TruyVanLayout.createSequentialGroup()
                .addGroup(jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn_TruyVanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Thang)
                            .addComponent(cbo_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Nam)
                            .addComponent(cbo_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpn_TruyVanLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jpn_nutTruyVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        txt_CanHo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_TienInternet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jpn_Sua.setBackground(new java.awt.Color(153, 204, 0));
        jpn_Sua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpn_Sua.setMaximumSize(new java.awt.Dimension(99, 36));
        jpn_Sua.setMinimumSize(new java.awt.Dimension(99, 36));
        jpn_Sua.setPreferredSize(new java.awt.Dimension(99, 36));

        lbl_Sua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Sua.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Maintenance.png"))); // NOI18N
        lbl_Sua.setText("Sửa");

        javax.swing.GroupLayout jpn_SuaLayout = new javax.swing.GroupLayout(jpn_Sua);
        jpn_Sua.setLayout(jpn_SuaLayout);
        jpn_SuaLayout.setHorizontalGroup(
            jpn_SuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_SuaLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lbl_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpn_SuaLayout.setVerticalGroup(
            jpn_SuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Sua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpn_Nhap.setBackground(new java.awt.Color(153, 204, 0));
        jpn_Nhap.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpn_Nhap.setMaximumSize(new java.awt.Dimension(99, 36));
        jpn_Nhap.setMinimumSize(new java.awt.Dimension(99, 36));

        lbl_Nhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Nhap.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Wite.png"))); // NOI18N
        lbl_Nhap.setText("Nhập ");

        javax.swing.GroupLayout jpn_NhapLayout = new javax.swing.GroupLayout(jpn_Nhap);
        jpn_Nhap.setLayout(jpn_NhapLayout);
        jpn_NhapLayout.setHorizontalGroup(
            jpn_NhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_NhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Nhap, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
        );
        jpn_NhapLayout.setVerticalGroup(
            jpn_NhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Nhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jpn_TaoHDThang.setBackground(new java.awt.Color(153, 204, 0));
        jpn_TaoHDThang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_TaoHDThang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TaoHDThang.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TaoHDThang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/New.png"))); // NOI18N
        lbl_TaoHDThang.setText("Tạo Hóa Đơn Tháng");

        javax.swing.GroupLayout jpn_TaoHDThangLayout = new javax.swing.GroupLayout(jpn_TaoHDThang);
        jpn_TaoHDThang.setLayout(jpn_TaoHDThangLayout);
        jpn_TaoHDThangLayout.setHorizontalGroup(
            jpn_TaoHDThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_TaoHDThangLayout.createSequentialGroup()
                .addComponent(lbl_TaoHDThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpn_TaoHDThangLayout.setVerticalGroup(
            jpn_TaoHDThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TaoHDThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpn_TacVuLayout = new javax.swing.GroupLayout(jpn_TacVu);
        jpn_TacVu.setLayout(jpn_TacVuLayout);
        jpn_TacVuLayout.setHorizontalGroup(
            jpn_TacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_TacVuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpn_TacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn_TacVuLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jpn_Nhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21)
                        .addComponent(jpn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jpn_TaoHDThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(jpn_TacVuLayout.createSequentialGroup()
                        .addGroup(jpn_TacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpn_TacVuLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lbl_CanHo)
                                .addGap(18, 18, 18)
                                .addComponent(txt_CanHo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpn_TacVuLayout.createSequentialGroup()
                                .addComponent(lbl_TienInternet)
                                .addGap(18, 18, 18)
                                .addComponent(txt_TienInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)))
                .addComponent(jpn_TruyVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jpn_TacVuLayout.setVerticalGroup(
            jpn_TacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_TacVuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jpn_TacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpn_TruyVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpn_TacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jpn_TaoHDThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpn_TacVuLayout.createSequentialGroup()
                            .addGroup(jpn_TacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpn_TacVuLayout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(lbl_CanHo))
                                .addComponent(txt_CanHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(35, 35, 35)
                            .addGroup(jpn_TacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_TienInternet)
                                .addComponent(txt_TienInternet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(37, 37, 37)
                            .addGroup(jpn_TacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jpn_Nhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jpn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        add(jpn_TacVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_NamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_NamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_Nam;
    private javax.swing.JComboBox<String> cbo_Thang;
    private javax.swing.JPanel jpn_Nhap;
    private javax.swing.JPanel jpn_Sua;
    private javax.swing.JPanel jpn_TacVu;
    private javax.swing.JPanel jpn_TaoHDThang;
    private javax.swing.JPanel jpn_TruyVan;
    private javax.swing.JPanel jpn_nutTruyVan;
    private javax.swing.JLabel lbl_CanHo;
    private javax.swing.JLabel lbl_Nam;
    private javax.swing.JLabel lbl_Nhap;
    private javax.swing.JLabel lbl_Sua;
    private javax.swing.JLabel lbl_TaoHDThang;
    private javax.swing.JLabel lbl_Thang;
    private javax.swing.JLabel lbl_TienInternet;
    private javax.swing.JLabel lbl_TruyVan;
    private javax.swing.JScrollPane tbl_BangInternet;
    private javax.swing.JTable tbl_ChiTietInternet;
    private javax.swing.JTextField txt_CanHo;
    private javax.swing.JTextField txt_TienInternet;
    // End of variables declaration//GEN-END:variables
}
