/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duan.UI;

import duan.JDBC.JDBC;
import duan.JDBC.XuLy;
import static duan.JDBC.XuLy.loaiboKhoangTrang;
import java.sql.ResultSet;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author anhdu
 */
public class MailThongBaoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MailThongBaoJPanel
     */
    public MailThongBaoJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMailThongBao = new javax.swing.JPanel();
        lblTang = new javax.swing.JLabel();
        lblThongBaoCanHo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        lblGuiMaiThongBao = new javax.swing.JLabel();
        lblGuiChoCanHo = new javax.swing.JLabel();
        cbo_GuiToanChungCu = new javax.swing.JCheckBox();
        txt_GuiChoCanHo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1040, 660));
        setMinimumSize(new java.awt.Dimension(1040, 660));

        pnlMailThongBao.setBackground(new java.awt.Color(0, 102, 102));
        pnlMailThongBao.setMaximumSize(new java.awt.Dimension(1040, 127));
        pnlMailThongBao.setMinimumSize(new java.awt.Dimension(1040, 127));
        pnlMailThongBao.setPreferredSize(new java.awt.Dimension(1040, 127));
        pnlMailThongBao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTang.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTang.setForeground(new java.awt.Color(255, 255, 255));
        lblTang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTang.setText("GỬI MAIL THÔNG BÁO");
        pnlMailThongBao.add(lblTang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 120));

        lblThongBaoCanHo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblThongBaoCanHo.setForeground(new java.awt.Color(255, 153, 153));
        pnlMailThongBao.add(lblThongBaoCanHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 400, 40));

        txtMessage.setColumns(20);
        txtMessage.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtMessage.setRows(5);
        jScrollPane1.setViewportView(txtMessage);

        lblGuiMaiThongBao.setBackground(new java.awt.Color(153, 204, 0));
        lblGuiMaiThongBao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGuiMaiThongBao.setForeground(new java.awt.Color(255, 255, 255));
        lblGuiMaiThongBao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuiMaiThongBao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Mail_25px.png"))); // NOI18N
        lblGuiMaiThongBao.setText("  Gửi Mail Thông Báo");
        lblGuiMaiThongBao.setOpaque(true);
        lblGuiMaiThongBao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblGuiMaiThongBaoMousePressed(evt);
            }
        });

        lblGuiChoCanHo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblGuiChoCanHo.setText("Gửi Cho Căn Hộ");

        cbo_GuiToanChungCu.setBackground(new java.awt.Color(255, 255, 255));
        cbo_GuiToanChungCu.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cbo_GuiToanChungCu.setText("Gửi Toàn Chung Cư");
        cbo_GuiToanChungCu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbo_GuiToanChungCuMouseClicked(evt);
            }
        });

        txt_GuiChoCanHo.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMailThongBao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGuiMaiThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(396, 396, 396))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGuiChoCanHo)
                                .addGap(70, 70, 70)
                                .addComponent(txt_GuiChoCanHo))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(cbo_GuiToanChungCu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMailThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGuiChoCanHo)
                    .addComponent(txt_GuiChoCanHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(cbo_GuiToanChungCu)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGuiMaiThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblGuiMaiThongBaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuiMaiThongBaoMousePressed
        if (check()) {
            this.GuiMail();
        }
    }//GEN-LAST:event_lblGuiMaiThongBaoMousePressed

    private void cbo_GuiToanChungCuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbo_GuiToanChungCuMouseClicked
        check = 1;
    }//GEN-LAST:event_cbo_GuiToanChungCuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbo_GuiToanChungCu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGuiChoCanHo;
    private javax.swing.JLabel lblGuiMaiThongBao;
    private javax.swing.JLabel lblTang;
    private javax.swing.JLabel lblThongBaoCanHo;
    private javax.swing.JPanel pnlMailThongBao;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextField txt_GuiChoCanHo;
    // End of variables declaration//GEN-END:variables
int check = 0;

    String canHOID() {
        String CanHoID = "";
        ResultSet rs = JDBC.executeQuery("SELECT CanHoId FROM dbo.CanHo WHERE MaSoCanHo = ?", txt_GuiChoCanHo.getText());
        try {
            if (rs.next()) {
                CanHoID = rs.getString(1);
            }
        } catch (Exception e) {
        }
        return CanHoID;
    }

    public void GuiMail() {

        try {
            if (!txt_GuiChoCanHo.getText().equals("")) {
                ResultSet rs1 = JDBC.executeQuery("SELECT KH.TenKhachHang,KH.Email,CH.MaSoCanHo "
                        + "FROM dbo.ThongTinKhachHang KH JOIN dbo.CanHo CH ON CH.CanHoId = KH.CanHoId WHERE KH.ChuHo = 1 AND CH.CanHoId = ?", canHOID());
                if (rs1.next()) {
                    String HoTen = rs1.getString(1);
                    String Email = rs1.getString(2);
                    String MaSoCH = rs1.getString(3);
                    Properties p = new Properties();
                    p.put("mail.smtp.auth", "true");
                    p.put("mail.smtp.starttls.enable", "true");
                    p.put("mail.smtp.host", "smtp.gmail.com");
                    p.put("mail.smtp.port", 587);

                    String accountName = "tamlnps08175@fpt.edu.vn";
                    String accountPassword = "lengoctam12";
                    Session s = Session.getInstance(p,
                            new javax.mail.Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication() {
                            return new PasswordAuthentication(accountName, accountPassword);
                        }
                    });

                    String from = "QuanLyChungCu";
                    String to = Email;
                    String subject = "Thông Báo Chung Cư";
                    String body = "Kính Gửi Anh(Chị): " + HoTen
                            + "\nCăn Hộ: " + MaSoCH + "\n\n"
                            + "Ban quản lý Chung Cư MILLENNIUM Xin Trân Trọng Thông Báo \n\n"
                            + txtMessage.getText()
                            + "\nTrân Trọng! \n\nP/S: Đây là mail tự động vui lòng không trả lời lại!";

                    Message msg = new MimeMessage(s);
                    msg.setFrom(new InternetAddress(from));
                    msg.setRecipients(Message.RecipientType.CC, InternetAddress.parse(to));
                    msg.setSubject(subject);

                    msg.setText(body);
                    Transport.send(msg);
                    JOptionPane.showMessageDialog(this, "Gửi Mail cho căn hộ " + MaSoCH + " thành công !");
                    txtMessage.setText("");
                    txt_GuiChoCanHo.setText("");
                    check = 0;
                    cbo_GuiToanChungCu.setSelected(false);
                }
            } else if (cbo_GuiToanChungCu.isSelected()) {
                String Email = "";
                ResultSet rs2 = JDBC.executeQuery("SELECT KH.Email FROM dbo.ThongTinKhachHang KH JOIN dbo.CanHo CH ON CH.CanHoId = KH.CanHoId WHERE ChuHo = 1");
                while (rs2.next()) {
                    Email += rs2.getString(1) + ",";
                }
                Properties p = new Properties();
                p.put("mail.smtp.auth", "true");
                p.put("mail.smtp.starttls.enable", "true");
                p.put("mail.smtp.host", "smtp.gmail.com");
                p.put("mail.smtp.port", 587);

                String accountName = "tamlnps08175@fpt.edu.vn";
                String accountPassword = "lengoctam12";
                Session s = Session.getInstance(p,
                        new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(accountName, accountPassword);
                    }
                });
                System.out.println(Email);

                String from = "QuanLyChungCu";
                String to = Email;
                String subject = "Thông Báo Chung Cư";
                String body = "Kính Gửi cư dân Chung Cư MILLENNIUM \n\n"
                        + "Ban quản lý Chung Cư MILLENNIUM Xin Trân Trọng Thông Báo \n\n"
                        + txtMessage.getText()
                        + "\nTrân Trọng! \n\nP/S: Đây là mail tự động vui lòng không trả lời lại!";

                Message msg = new MimeMessage(s);
                msg.setFrom(new InternetAddress(from));
                msg.setRecipients(Message.RecipientType.CC, InternetAddress.parse(to));
                msg.setSubject(subject);

                msg.setText(body);
                Transport.send(msg);

                JOptionPane.showMessageDialog(this, "Gửi Mail thành công !");
                txtMessage.setText("");
                txt_GuiChoCanHo.setText("");
                check = 0;
                cbo_GuiToanChungCu.setSelected(false);
            }

        } catch (Exception e) {
            System.err.println(e);
        }
    }

    boolean check() {
        if (txt_GuiChoCanHo.getText().trim().equals("") && check == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhâp số căn hộ hoặc check vào Gửi Toàn Chung Cư để gửi mail");
            txt_GuiChoCanHo.setVisible(true);
            return false;
        }else if (txtMessage.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Nội dung mail không có");
            txtMessage.setVisible(true);
            return false;
        }else if (!loaiboKhoangTrang(txtMessage.getText().trim()).matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Số mã số căn hộ không được chứa kí tự!");
            txt_GuiChoCanHo.setVisible(true);
            return false;
        }
        return true;
    }

}
