/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duan.UI;

import duan.Bean.DanhMucBean;
import duan.Controller.ChuyenManHinhController;
import java.util.ArrayList;
import java.util.List;
 
/**
 *
 * @author anhdu
 */
public class mainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public mainJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Công Cụ Quản Lý Chung Cư");
        
        
        ChuyenManHinhController controller = new ChuyenManHinhController(jpn_View);
        controller.setView(jpn_TrangChu, jlbTrangChu);
        
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("TrangChu", jpn_TrangChu, jlbTrangChu));
        listItem.add(new DanhMucBean("CanHo", jpn_CanHo, jlbCanHo));
        listItem.add(new DanhMucBean("DichVu", jpn_DichVu, jlbDichVu));

        
        controller.setEvent(listItem);
    }
    int xMouse, yMouse;
    ThongTinTK thongTinAcc = new ThongTinTK();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_Tong = new javax.swing.JPanel();
        btn_Minimize = new javax.swing.JLabel();
        btn_Close = new javax.swing.JLabel();
        lbl_CongCuQuanLyChungCu = new javax.swing.JLabel();
        lbl_Titlebar = new javax.swing.JLabel();
        pnl_Menu = new javax.swing.JPanel();
        jpn_QLCC = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpn_TrangChu = new javax.swing.JPanel();
        jlbTrangChu = new javax.swing.JLabel();
        jpn_CanHo = new javax.swing.JPanel();
        jlbCanHo = new javax.swing.JLabel();
        lbl_nhom6 = new javax.swing.JLabel();
        jpn_DichVu = new javax.swing.JPanel();
        jlbDichVu = new javax.swing.JLabel();
        jpn_ThongTin = new javax.swing.JPanel();
        jlbThongTin = new javax.swing.JLabel();
        jpn_View = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setUndecorated(true);

        jpn_Tong.setBackground(new java.awt.Color(255, 255, 255));
        jpn_Tong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jpn_Tong.setMaximumSize(new java.awt.Dimension(1300, 700));
        jpn_Tong.setMinimumSize(new java.awt.Dimension(1300, 700));
        jpn_Tong.setPreferredSize(new java.awt.Dimension(1300, 700));
        jpn_Tong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Minimize.png"))); // NOI18N
        btn_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MinimizeMouseClicked(evt);
            }
        });
        jpn_Tong.add(btn_Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, -1, -1));

        btn_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Close.png"))); // NOI18N
        btn_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CloseMouseClicked(evt);
            }
        });
        jpn_Tong.add(btn_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, -1, -1));

        lbl_CongCuQuanLyChungCu.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        lbl_CongCuQuanLyChungCu.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CongCuQuanLyChungCu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CongCuQuanLyChungCu.setText("Công Cụ Quản Lý Chung Cư ");
        jpn_Tong.add(lbl_CongCuQuanLyChungCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbl_Titlebar.setBackground(new java.awt.Color(0, 153, 153));
        lbl_Titlebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Titlebar_background2.png"))); // NOI18N
        lbl_Titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbl_TitlebarMouseDragged(evt);
            }
        });
        lbl_Titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_TitlebarMousePressed(evt);
            }
        });
        jpn_Tong.add(lbl_Titlebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 40));

        pnl_Menu.setBackground(new java.awt.Color(0, 51, 51));
        pnl_Menu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(102, 102, 102)));

        jpn_QLCC.setBackground(new java.awt.Color(255, 102, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ CHUNG CƯ");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/LogoMain.png"))); // NOI18N

        javax.swing.GroupLayout jpn_QLCCLayout = new javax.swing.GroupLayout(jpn_QLCC);
        jpn_QLCC.setLayout(jpn_QLCCLayout);
        jpn_QLCCLayout.setHorizontalGroup(
            jpn_QLCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpn_QLCCLayout.setVerticalGroup(
            jpn_QLCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_QLCCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jpn_TrangChu.setBackground(new java.awt.Color(121, 196, 71));

        jlbTrangChu.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        jlbTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Menu1.png"))); // NOI18N
        jlbTrangChu.setText("    Màn Hình Chính");

        javax.swing.GroupLayout jpn_TrangChuLayout = new javax.swing.GroupLayout(jpn_TrangChu);
        jpn_TrangChu.setLayout(jpn_TrangChuLayout);
        jpn_TrangChuLayout.setHorizontalGroup(
            jpn_TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );
        jpn_TrangChuLayout.setVerticalGroup(
            jpn_TrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbTrangChu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jpn_CanHo.setBackground(new java.awt.Color(121, 196, 71));

        jlbCanHo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbCanHo.setForeground(new java.awt.Color(255, 255, 255));
        jlbCanHo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCanHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Home2.png"))); // NOI18N
        jlbCanHo.setText("    Quản Lý Căn Hộ");

        javax.swing.GroupLayout jpn_CanHoLayout = new javax.swing.GroupLayout(jpn_CanHo);
        jpn_CanHo.setLayout(jpn_CanHoLayout);
        jpn_CanHoLayout.setHorizontalGroup(
            jpn_CanHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbCanHo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpn_CanHoLayout.setVerticalGroup(
            jpn_CanHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbCanHo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        lbl_nhom6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_nhom6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nhom6.setText("Nhóm 6 - PT14101");

        jpn_DichVu.setBackground(new java.awt.Color(121, 196, 71));

        jlbDichVu.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbDichVu.setForeground(new java.awt.Color(255, 255, 255));
        jlbDichVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Support.png"))); // NOI18N
        jlbDichVu.setText("   Quản Lý Dịch Vụ");

        javax.swing.GroupLayout jpn_DichVuLayout = new javax.swing.GroupLayout(jpn_DichVu);
        jpn_DichVu.setLayout(jpn_DichVuLayout);
        jpn_DichVuLayout.setHorizontalGroup(
            jpn_DichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpn_DichVuLayout.setVerticalGroup(
            jpn_DichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbDichVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jpn_ThongTin.setBackground(new java.awt.Color(121, 196, 71));
        jpn_ThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_ThongTinMouseClicked(evt);
            }
        });

        jlbThongTin.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbThongTin.setForeground(new java.awt.Color(255, 255, 255));
        jlbThongTin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Account.png"))); // NOI18N
        jlbThongTin.setText("Thông Tin Tài Khoản");

        javax.swing.GroupLayout jpn_ThongTinLayout = new javax.swing.GroupLayout(jpn_ThongTin);
        jpn_ThongTin.setLayout(jpn_ThongTinLayout);
        jpn_ThongTinLayout.setHorizontalGroup(
            jpn_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );
        jpn_ThongTinLayout.setVerticalGroup(
            jpn_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbThongTin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_MenuLayout = new javax.swing.GroupLayout(pnl_Menu);
        pnl_Menu.setLayout(pnl_MenuLayout);
        pnl_MenuLayout.setHorizontalGroup(
            pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_QLCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_nhom6)
                .addGap(71, 71, 71))
            .addGroup(pnl_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpn_DichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpn_CanHo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpn_ThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_MenuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpn_TrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnl_MenuLayout.setVerticalGroup(
            pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MenuLayout.createSequentialGroup()
                .addComponent(jpn_QLCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145)
                .addComponent(jpn_CanHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpn_DichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jpn_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_nhom6)
                .addContainerGap())
            .addGroup(pnl_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_MenuLayout.createSequentialGroup()
                    .addGap(180, 180, 180)
                    .addComponent(jpn_TrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(409, Short.MAX_VALUE)))
        );

        jpn_Tong.add(pnl_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 260, 660));

        jpn_View.setBackground(new java.awt.Color(255, 255, 255));
        jpn_View.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(102, 102, 102)));
        jpn_View.setMaximumSize(new java.awt.Dimension(1040, 660));
        jpn_View.setMinimumSize(new java.awt.Dimension(1040, 660));

        javax.swing.GroupLayout jpn_ViewLayout = new javax.swing.GroupLayout(jpn_View);
        jpn_View.setLayout(jpn_ViewLayout);
        jpn_ViewLayout.setHorizontalGroup(
            jpn_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1039, Short.MAX_VALUE)
        );
        jpn_ViewLayout.setVerticalGroup(
            jpn_ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        jpn_Tong.add(jpn_View, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 1040, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_Tong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn_Tong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_TitlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TitlebarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_lbl_TitlebarMouseDragged

    private void lbl_TitlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TitlebarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_lbl_TitlebarMousePressed

    private void btn_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_CloseMouseClicked

    private void btn_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MinimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btn_MinimizeMouseClicked

    private void jpn_ThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_ThongTinMouseClicked
        thongTinAcc.setVisible(true);
    }//GEN-LAST:event_jpn_ThongTinMouseClicked

    /*********
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Close;
    private javax.swing.JLabel btn_Minimize;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlbCanHo;
    private javax.swing.JLabel jlbDichVu;
    private javax.swing.JLabel jlbThongTin;
    private javax.swing.JLabel jlbTrangChu;
    private javax.swing.JPanel jpn_CanHo;
    private javax.swing.JPanel jpn_DichVu;
    private javax.swing.JPanel jpn_QLCC;
    private javax.swing.JPanel jpn_ThongTin;
    private javax.swing.JPanel jpn_Tong;
    private javax.swing.JPanel jpn_TrangChu;
    private javax.swing.JPanel jpn_View;
    private javax.swing.JLabel lbl_CongCuQuanLyChungCu;
    private javax.swing.JLabel lbl_Titlebar;
    private javax.swing.JLabel lbl_nhom6;
    private javax.swing.JPanel pnl_Menu;
    // End of variables declaration//GEN-END:variables
}
