/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duan.UI;

/**
 *
 * @author anhdu
 */
public class SinhHoatJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DichVu_HoaDonJPanel
     */
    public SinhHoatJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_ThanhCongCu = new javax.swing.JPanel();
        jpn_TruyVan = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lbl_CanHo = new javax.swing.JLabel();
        lbl_ChiSoDienDau = new javax.swing.JLabel();
        lbl_ChiSoNuocDau = new javax.swing.JLabel();
        lbl_ChiSoDienCuoi = new javax.swing.JLabel();
        lbl_ChiSoNuocCuoi = new javax.swing.JLabel();
        lbl_TienDien = new javax.swing.JLabel();
        lbl_TienNuoc = new javax.swing.JLabel();
        txt_CanHo = new javax.swing.JTextField();
        txt_ChiSoDienDau = new javax.swing.JTextField();
        txt_ChiSoDienCuoi = new javax.swing.JTextField();
        txt_ChiSoNuocCuoi = new javax.swing.JTextField();
        txt_ChiSoNuocDau = new javax.swing.JTextField();
        lbl_GiaTienDien = new javax.swing.JLabel();
        lbl_GiaTienNuoc = new javax.swing.JLabel();
        jpn_TaoHDThang = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpn_Sua = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jpn_Nhap = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tbl_BangThongKe = new javax.swing.JScrollPane();
        tbl_ThongKe = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1040, 610));
        setMinimumSize(new java.awt.Dimension(1040, 610));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpn_ThanhCongCu.setBackground(new java.awt.Color(255, 255, 255));
        jpn_ThanhCongCu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jpn_ThanhCongCu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpn_TruyVan.setBackground(new java.awt.Color(255, 255, 255));
        jpn_TruyVan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Truy Vấn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Tháng");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Năm");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel8.setBackground(new java.awt.Color(255, 102, 102));
        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Search_25px.png"))); // NOI18N
        jLabel13.setText("Truy Vấn");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpn_TruyVanLayout = new javax.swing.GroupLayout(jpn_TruyVan);
        jpn_TruyVan.setLayout(jpn_TruyVanLayout);
        jpn_TruyVanLayout.setHorizontalGroup(
            jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_TruyVanLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_TruyVanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jpn_TruyVanLayout.setVerticalGroup(
            jpn_TruyVanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_TruyVanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpn_ThanhCongCu.add(jpn_TruyVan, new org.netbeans.lib.awtextra.AbsoluteConstraints(778, 27, 220, -1));

        lbl_CanHo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_CanHo.setText("Căn Hộ");
        jpn_ThanhCongCu.add(lbl_CanHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 29, -1, -1));

        lbl_ChiSoDienDau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ChiSoDienDau.setText("Chỉ Số Điện Đầu");
        jpn_ThanhCongCu.add(lbl_ChiSoDienDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 100, -1, -1));

        lbl_ChiSoNuocDau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ChiSoNuocDau.setText("Chỉ Số Nước Đầu");
        jpn_ThanhCongCu.add(lbl_ChiSoNuocDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 100, -1, -1));

        lbl_ChiSoDienCuoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ChiSoDienCuoi.setText("Chỉ Số Điện Cuối");
        jpn_ThanhCongCu.add(lbl_ChiSoDienCuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 164, -1, -1));

        lbl_ChiSoNuocCuoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ChiSoNuocCuoi.setText("Chỉ Số Nước Cuối");
        jpn_ThanhCongCu.add(lbl_ChiSoNuocCuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 164, -1, -1));

        lbl_TienDien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TienDien.setText("Tiền Điện");
        jpn_ThanhCongCu.add(lbl_TienDien, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 220, -1, -1));

        lbl_TienNuoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_TienNuoc.setText("Tiền Nước");
        jpn_ThanhCongCu.add(lbl_TienNuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 220, -1, -1));
        jpn_ThanhCongCu.add(txt_CanHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 27, 132, -1));
        jpn_ThanhCongCu.add(txt_ChiSoDienDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 98, 129, -1));
        jpn_ThanhCongCu.add(txt_ChiSoDienCuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 162, 126, -1));
        jpn_ThanhCongCu.add(txt_ChiSoNuocCuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 162, 126, -1));
        jpn_ThanhCongCu.add(txt_ChiSoNuocDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 98, 129, -1));

        lbl_GiaTienDien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_GiaTienDien.setForeground(new java.awt.Color(255, 0, 0));
        lbl_GiaTienDien.setText("100,000");
        jpn_ThanhCongCu.add(lbl_GiaTienDien, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 218, -1, -1));

        lbl_GiaTienNuoc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_GiaTienNuoc.setForeground(new java.awt.Color(255, 0, 0));
        lbl_GiaTienNuoc.setText("100,000");
        jpn_ThanhCongCu.add(lbl_GiaTienNuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 218, -1, -1));

        jpn_TaoHDThang.setBackground(new java.awt.Color(153, 204, 0));
        jpn_TaoHDThang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/New.png"))); // NOI18N
        jLabel10.setText("Tạo Hóa Đơn Tháng");

        javax.swing.GroupLayout jpn_TaoHDThangLayout = new javax.swing.GroupLayout(jpn_TaoHDThang);
        jpn_TaoHDThang.setLayout(jpn_TaoHDThangLayout);
        jpn_TaoHDThangLayout.setHorizontalGroup(
            jpn_TaoHDThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_TaoHDThangLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpn_TaoHDThangLayout.setVerticalGroup(
            jpn_TaoHDThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpn_ThanhCongCu.add(jpn_TaoHDThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        jpn_Sua.setBackground(new java.awt.Color(153, 204, 0));
        jpn_Sua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Maintenance.png"))); // NOI18N
        jLabel11.setText("Sửa");

        javax.swing.GroupLayout jpn_SuaLayout = new javax.swing.GroupLayout(jpn_Sua);
        jpn_Sua.setLayout(jpn_SuaLayout);
        jpn_SuaLayout.setHorizontalGroup(
            jpn_SuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_SuaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpn_SuaLayout.setVerticalGroup(
            jpn_SuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jpn_ThanhCongCu.add(jpn_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 162, 100, -1));

        jpn_Nhap.setBackground(new java.awt.Color(153, 204, 0));
        jpn_Nhap.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Wite.png"))); // NOI18N
        jLabel12.setText("Nhập ");

        javax.swing.GroupLayout jpn_NhapLayout = new javax.swing.GroupLayout(jpn_Nhap);
        jpn_Nhap.setLayout(jpn_NhapLayout);
        jpn_NhapLayout.setHorizontalGroup(
            jpn_NhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpn_NhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
        );
        jpn_NhapLayout.setVerticalGroup(
            jpn_NhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jpn_ThanhCongCu.add(jpn_Nhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 98, -1, -1));

        add(jpn_ThanhCongCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 265));

        tbl_ThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Căn Hộ", "Chỉ Số Điện Đầu", "Chỉ Số Điện Cuối", "Tiền Điện", "Chỉ Số Nước Đầu", "Chỉ Số Nước Cuối", "Tiền Nước"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_BangThongKe.setViewportView(tbl_ThongKe);

        add(tbl_BangThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 278, 1016, 304));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jpn_Nhap;
    private javax.swing.JPanel jpn_Sua;
    private javax.swing.JPanel jpn_TaoHDThang;
    private javax.swing.JPanel jpn_ThanhCongCu;
    private javax.swing.JPanel jpn_TruyVan;
    private javax.swing.JLabel lbl_CanHo;
    private javax.swing.JLabel lbl_ChiSoDienCuoi;
    private javax.swing.JLabel lbl_ChiSoDienDau;
    private javax.swing.JLabel lbl_ChiSoNuocCuoi;
    private javax.swing.JLabel lbl_ChiSoNuocDau;
    private javax.swing.JLabel lbl_GiaTienDien;
    private javax.swing.JLabel lbl_GiaTienNuoc;
    private javax.swing.JLabel lbl_TienDien;
    private javax.swing.JLabel lbl_TienNuoc;
    private javax.swing.JScrollPane tbl_BangThongKe;
    private javax.swing.JTable tbl_ThongKe;
    private javax.swing.JTextField txt_CanHo;
    private javax.swing.JTextField txt_ChiSoDienCuoi;
    private javax.swing.JTextField txt_ChiSoDienDau;
    private javax.swing.JTextField txt_ChiSoNuocCuoi;
    private javax.swing.JTextField txt_ChiSoNuocDau;
    // End of variables declaration//GEN-END:variables
}
