/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duan.UI;

import java.awt.Color;

/**
 *
 * @author anhdu
 */
public class ThongTinTK extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinTK
     */
    public ThongTinTK() {

        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
        this.setTitle("Thông Tin Tài Khoản");
    }
    int yMouse, xMouse;
    int Dem = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpn_Minimize = new javax.swing.JLabel();
        jpn_Close = new javax.swing.JLabel();
        lbl_Tile = new javax.swing.JLabel();
        lbl_Titlebar = new javax.swing.JLabel();
        jtl_Main = new javax.swing.JTabbedPane();
        jpn_ThongTin = new javax.swing.JPanel();
        lbl_HovaTen = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_SoDT = new javax.swing.JLabel();
        txt_HovaTen = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_SoDT = new javax.swing.JTextField();
        jpn_CapNhat = new javax.swing.JPanel();
        lbl_CapNhat = new javax.swing.JLabel();
        jpn_DoiMK = new javax.swing.JPanel();
        lbl_MkCu = new javax.swing.JLabel();
        lbl_MkMoi = new javax.swing.JLabel();
        lbl_NhapLaiMk = new javax.swing.JLabel();
        txt_MatKhauCu = new javax.swing.JPasswordField();
        txt_MatKhauMoi = new javax.swing.JPasswordField();
        txt_NhapLaiMatKhau = new javax.swing.JPasswordField();
        jpn_DoiMatKhau = new javax.swing.JPanel();
        jlbDoiMatKhau = new javax.swing.JLabel();
        lbl_ShowMkCu = new javax.swing.JLabel();
        lbl_ShowMkMoi = new javax.swing.JLabel();
        lbl_ShowMkNLMK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thông Tin Tài Khoản");
        setMaximumSize(new java.awt.Dimension(470, 365));
        setMinimumSize(new java.awt.Dimension(470, 365));
        setUndecorated(true);
        setResizable(false);

        jpn_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Minimize.png"))); // NOI18N
        jpn_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_MinimizeMouseClicked(evt);
            }
        });

        jpn_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Close.png"))); // NOI18N
        jpn_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_CloseMouseClicked(evt);
            }
        });

        lbl_Tile.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        lbl_Tile.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Tile.setText("Thông Tin Tài Khoản");

        lbl_Titlebar.setBackground(new java.awt.Color(0, 153, 153));
        lbl_Titlebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Titlebar_background2.png"))); // NOI18N
        lbl_Titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbl_TitlebarMouseDragged(evt);
            }
        });
        lbl_Titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_TitlebarMousePressed(evt);
            }
        });

        jtl_Main.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        jpn_ThongTin.setBackground(new java.awt.Color(255, 255, 255));

        lbl_HovaTen.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbl_HovaTen.setText("Họ và Tên");

        lbl_Email.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbl_Email.setText("Email");

        lbl_SoDT.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbl_SoDT.setText("Số Điện Thoại");

        txt_HovaTen.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_HovaTen.setToolTipText("Họ và Tên");

        txt_Email.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_Email.setToolTipText("Email");

        txt_SoDT.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txt_SoDT.setToolTipText("Số Điện Thoại");

        jpn_CapNhat.setBackground(new java.awt.Color(255, 102, 102));
        jpn_CapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_CapNhatMouseClicked(evt);
            }
        });

        lbl_CapNhat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_CapNhat.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CapNhat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CapNhat.setText("Cập Nhật");

        javax.swing.GroupLayout jpn_CapNhatLayout = new javax.swing.GroupLayout(jpn_CapNhat);
        jpn_CapNhat.setLayout(jpn_CapNhatLayout);
        jpn_CapNhatLayout.setHorizontalGroup(
            jpn_CapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_CapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        jpn_CapNhatLayout.setVerticalGroup(
            jpn_CapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_CapNhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpn_ThongTinLayout = new javax.swing.GroupLayout(jpn_ThongTin);
        jpn_ThongTin.setLayout(jpn_ThongTinLayout);
        jpn_ThongTinLayout.setHorizontalGroup(
            jpn_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_ThongTinLayout.createSequentialGroup()
                .addGroup(jpn_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn_ThongTinLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jpn_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpn_ThongTinLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpn_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_SoDT)
                            .addComponent(lbl_Email)
                            .addComponent(lbl_HovaTen))
                        .addGap(30, 30, 30)
                        .addGroup(jpn_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_HovaTen)
                            .addComponent(txt_Email)
                            .addComponent(txt_SoDT, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jpn_ThongTinLayout.setVerticalGroup(
            jpn_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_ThongTinLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jpn_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_HovaTen)
                    .addComponent(txt_HovaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jpn_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Email)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jpn_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SoDT)
                    .addComponent(txt_SoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jpn_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jtl_Main.addTab("Thông Tin Tài Khoản", jpn_ThongTin);

        jpn_DoiMK.setBackground(new java.awt.Color(255, 255, 255));

        lbl_MkCu.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbl_MkCu.setText("Mật Khẩu Cũ");

        lbl_MkMoi.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbl_MkMoi.setText("Mật Khẩu Mới");

        lbl_NhapLaiMk.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbl_NhapLaiMk.setText("Nhập Lại Mật Khẩu");

        txt_MatKhauCu.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txt_MatKhauMoi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txt_NhapLaiMatKhau.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jpn_DoiMatKhau.setBackground(new java.awt.Color(255, 102, 102));
        jpn_DoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_DoiMatKhauMouseClicked(evt);
            }
        });

        jlbDoiMatKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        jlbDoiMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDoiMatKhau.setText("Đổi Mật Khẩu");

        javax.swing.GroupLayout jpn_DoiMatKhauLayout = new javax.swing.GroupLayout(jpn_DoiMatKhau);
        jpn_DoiMatKhau.setLayout(jpn_DoiMatKhauLayout);
        jpn_DoiMatKhauLayout.setHorizontalGroup(
            jpn_DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbDoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        jpn_DoiMatKhauLayout.setVerticalGroup(
            jpn_DoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbDoiMatKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        lbl_ShowMkCu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/InvisibleEye.png"))); // NOI18N
        lbl_ShowMkCu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ShowMkCuMouseClicked(evt);
            }
        });

        lbl_ShowMkMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/InvisibleEye.png"))); // NOI18N
        lbl_ShowMkMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ShowMkMoiMouseClicked(evt);
            }
        });

        lbl_ShowMkNLMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/InvisibleEye.png"))); // NOI18N
        lbl_ShowMkNLMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ShowMkNLMKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpn_DoiMKLayout = new javax.swing.GroupLayout(jpn_DoiMK);
        jpn_DoiMK.setLayout(jpn_DoiMKLayout);
        jpn_DoiMKLayout.setHorizontalGroup(
            jpn_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_DoiMKLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpn_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_MkCu)
                    .addComponent(lbl_MkMoi)
                    .addComponent(lbl_NhapLaiMk))
                .addGap(18, 18, 18)
                .addGroup(jpn_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpn_DoiMKLayout.createSequentialGroup()
                        .addComponent(jpn_DoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpn_DoiMKLayout.createSequentialGroup()
                        .addGroup(jpn_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpn_DoiMKLayout.createSequentialGroup()
                                .addComponent(txt_NhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_ShowMkNLMK))
                            .addGroup(jpn_DoiMKLayout.createSequentialGroup()
                                .addGroup(jpn_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpn_DoiMKLayout.createSequentialGroup()
                                        .addComponent(txt_MatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_ShowMkCu))
                                    .addGroup(jpn_DoiMKLayout.createSequentialGroup()
                                        .addComponent(txt_MatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_ShowMkMoi)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(13, Short.MAX_VALUE))))
        );
        jpn_DoiMKLayout.setVerticalGroup(
            jpn_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpn_DoiMKLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jpn_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MkCu)
                    .addComponent(txt_MatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ShowMkCu))
                .addGap(36, 36, 36)
                .addGroup(jpn_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MkMoi)
                    .addComponent(txt_MatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ShowMkMoi))
                .addGap(31, 31, 31)
                .addGroup(jpn_DoiMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NhapLaiMk)
                    .addComponent(txt_NhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ShowMkNLMK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jpn_DoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jtl_Main.addTab("Đổi Mật Khẩu", jpn_DoiMK);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_Tile, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addComponent(jpn_Minimize)
                .addGap(0, 0, 0)
                .addComponent(jpn_Close))
            .addComponent(lbl_Titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jtl_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_Tile))
                    .addComponent(jpn_Minimize)
                    .addComponent(jpn_Close)
                    .addComponent(lbl_Titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jtl_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpn_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jpn_CloseMouseClicked

    private void jpn_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_MinimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jpn_MinimizeMouseClicked

    private void lbl_TitlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TitlebarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_lbl_TitlebarMouseDragged

    private void lbl_TitlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TitlebarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_lbl_TitlebarMousePressed

    private void jpn_CapNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_CapNhatMouseClicked

    }//GEN-LAST:event_jpn_CapNhatMouseClicked

    private void jpn_DoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_DoiMatKhauMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpn_DoiMatKhauMouseClicked

    private void lbl_ShowMkCuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ShowMkCuMouseClicked
        if (Dem == 0) {
            txt_MatKhauCu.setEchoChar((char) 0);
            lbl_ShowMkCu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Eye.png")));
            Dem = -1;
        } else {
            txt_MatKhauCu.setEchoChar('*');
            lbl_ShowMkCu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/InvisibleEye.png")));
            Dem = 0;
        }
    }//GEN-LAST:event_lbl_ShowMkCuMouseClicked

    private void lbl_ShowMkMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ShowMkMoiMouseClicked
        if (Dem == 0) {
            txt_MatKhauMoi.setEchoChar((char) 0);
            lbl_ShowMkMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Eye.png")));
            Dem = -1;
        } else {
            txt_MatKhauMoi.setEchoChar('*');
            lbl_ShowMkMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/InvisibleEye.png")));
            Dem = 0;
        }
    }//GEN-LAST:event_lbl_ShowMkMoiMouseClicked

    private void lbl_ShowMkNLMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ShowMkNLMKMouseClicked
        if (Dem == 0) {
            txt_NhapLaiMatKhau.setEchoChar((char) 0);
            lbl_ShowMkNLMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Eye.png")));
            Dem = -1;
        } else {
            txt_NhapLaiMatKhau.setEchoChar('*');
            lbl_ShowMkNLMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/InvisibleEye.png")));
            Dem = 0;
        }
    }//GEN-LAST:event_lbl_ShowMkNLMKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinTK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinTK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbDoiMatKhau;
    private javax.swing.JPanel jpn_CapNhat;
    private javax.swing.JLabel jpn_Close;
    private javax.swing.JPanel jpn_DoiMK;
    private javax.swing.JPanel jpn_DoiMatKhau;
    private javax.swing.JLabel jpn_Minimize;
    private javax.swing.JPanel jpn_ThongTin;
    private javax.swing.JTabbedPane jtl_Main;
    private javax.swing.JLabel lbl_CapNhat;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_HovaTen;
    private javax.swing.JLabel lbl_MkCu;
    private javax.swing.JLabel lbl_MkMoi;
    private javax.swing.JLabel lbl_NhapLaiMk;
    private javax.swing.JLabel lbl_ShowMkCu;
    private javax.swing.JLabel lbl_ShowMkMoi;
    private javax.swing.JLabel lbl_ShowMkNLMK;
    private javax.swing.JLabel lbl_SoDT;
    private javax.swing.JLabel lbl_Tile;
    private javax.swing.JLabel lbl_Titlebar;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_HovaTen;
    private javax.swing.JPasswordField txt_MatKhauCu;
    private javax.swing.JPasswordField txt_MatKhauMoi;
    private javax.swing.JPasswordField txt_NhapLaiMatKhau;
    private javax.swing.JTextField txt_SoDT;
    // End of variables declaration//GEN-END:variables
}
