/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duan.UI;

import duan.DAO.ThongTinKhachHangDAO;
import duan.JDBC.JDBC;
import duan.model.ThongTinKhachHang;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anhdu
 */
public class ThongTinCanHoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThongTInCanHo
     */
    String masocanho, canhoID;

    public ThongTinCanHoJFrame(String masocanho, String canhoID) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.masocanho = masocanho;
        this.setTitle("Thông Tin Căn Hộ " + masocanho);
        lbl_Title.setText("Thông Tin Căn Hộ " + masocanho);
        this.canhoID = canhoID;
        this.loadThanhVien();
        this.loadChuHo();
        this.Logo();
    }
    int xMouse, yMouse;

    public void Logo() {
        ImageIcon img = new ImageIcon("src\\duan\\Logo\\LOGO.png");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGioiTinh = new javax.swing.ButtonGroup();
        btgGioiTinhTT = new javax.swing.ButtonGroup();
        pnlMain = new javax.swing.JPanel();
        sclKhachhang = new javax.swing.JScrollPane();
        tblKhachhang = new javax.swing.JTable();
        lbl_Title = new javax.swing.JLabel();
        jpn_Minimize = new javax.swing.JLabel();
        jpn_Close = new javax.swing.JLabel();
        lbl_Titlebar = new javax.swing.JLabel();
        pnlMainTab = new javax.swing.JTabbedPane();
        PnlThongTinChuSoHuu = new javax.swing.JPanel();
        txtmaKhachhangTT = new javax.swing.JTextField();
        lblMaKhachHangTT = new javax.swing.JLabel();
        lblTenKHTT = new javax.swing.JLabel();
        lblCMNDTT = new javax.swing.JLabel();
        txtCMNDTT = new javax.swing.JTextField();
        txtTenKHTT = new javax.swing.JTextField();
        txtSoDTTT = new javax.swing.JTextField();
        txtEmailTT = new javax.swing.JTextField();
        lblEmailTT = new javax.swing.JLabel();
        lblSoDTTT = new javax.swing.JLabel();
        lblGioiTinhTT = new javax.swing.JLabel();
        rdoNamTT = new javax.swing.JRadioButton();
        rdoNuTT = new javax.swing.JRadioButton();
        pnlThongTinThanhVien = new javax.swing.JPanel();
        lblTenKH = new javax.swing.JLabel();
        lblCMND = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblSoDT = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblChuHo = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        txtSoDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        cboCo = new javax.swing.JCheckBox();
        lblMaKhachHang = new javax.swing.JLabel();
        txtmaKhachhang = new javax.swing.JTextField();
        lblXoa = new javax.swing.JLabel();
        lblThem = new javax.swing.JLabel();
        pnlChuyenChuHo = new javax.swing.JPanel();
        lblTu = new javax.swing.JLabel();
        lblTenChuHo = new javax.swing.JLabel();
        lblDen = new javax.swing.JLabel();
        cboChuHoMoi = new javax.swing.JComboBox<>();
        lblChuyen = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblChuyenTu = new javax.swing.JLabel();
        lblChuSoHuuCu = new javax.swing.JLabel();
        lblSang = new javax.swing.JLabel();
        txtmaKHChuSoHuuMoi = new javax.swing.JTextField();
        lblMaKHChuSoHuuMoi = new javax.swing.JLabel();
        lblChuyenChuSoHuu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 530));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sclKhachhang.setToolTipText("Người trong căn hộ");
        sclKhachhang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tblKhachhang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblKhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "CMND", "Giới Tính", "Số ĐT", "Email", "CH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachhang.setToolTipText("Người Trong Căn Hộ");
        tblKhachhang.setMaximumSize(new java.awt.Dimension(450, 64));
        tblKhachhang.setMinimumSize(new java.awt.Dimension(450, 64));
        tblKhachhang.setRowHeight(20);
        tblKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachhangMouseClicked(evt);
            }
        });
        sclKhachhang.setViewportView(tblKhachhang);
        if (tblKhachhang.getColumnModel().getColumnCount() > 0) {
            tblKhachhang.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblKhachhang.getColumnModel().getColumn(0).setMaxWidth(100);
            tblKhachhang.getColumnModel().getColumn(1).setPreferredWidth(170);
            tblKhachhang.getColumnModel().getColumn(1).setMaxWidth(200);
            tblKhachhang.getColumnModel().getColumn(2).setPreferredWidth(110);
            tblKhachhang.getColumnModel().getColumn(2).setMaxWidth(110);
            tblKhachhang.getColumnModel().getColumn(3).setPreferredWidth(70);
            tblKhachhang.getColumnModel().getColumn(3).setMaxWidth(70);
            tblKhachhang.getColumnModel().getColumn(4).setPreferredWidth(110);
            tblKhachhang.getColumnModel().getColumn(4).setMaxWidth(110);
            tblKhachhang.getColumnModel().getColumn(6).setMinWidth(30);
            tblKhachhang.getColumnModel().getColumn(6).setPreferredWidth(30);
            tblKhachhang.getColumnModel().getColumn(6).setMaxWidth(30);
        }

        pnlMain.add(sclKhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 810, 200));

        lbl_Title.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("Thông Tin Căn Hộ");
        pnlMain.add(lbl_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jpn_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Minimize.png"))); // NOI18N
        jpn_Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_MinimizeMouseClicked(evt);
            }
        });
        pnlMain.add(jpn_Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        jpn_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Close.png"))); // NOI18N
        jpn_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpn_CloseMouseClicked(evt);
            }
        });
        pnlMain.add(jpn_Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, -1));

        lbl_Titlebar.setBackground(new java.awt.Color(0, 153, 153));
        lbl_Titlebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Titlebar_background2.png"))); // NOI18N
        lbl_Titlebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbl_TitlebarMouseDragged(evt);
            }
        });
        lbl_Titlebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_TitlebarMousePressed(evt);
            }
        });
        pnlMain.add(lbl_Titlebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 40));

        pnlMainTab.setBackground(new java.awt.Color(255, 255, 255));
        pnlMainTab.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 1, new java.awt.Color(102, 102, 102)));

        PnlThongTinChuSoHuu.setBackground(new java.awt.Color(255, 255, 255));

        txtmaKhachhangTT.setEditable(false);
        txtmaKhachhangTT.setBackground(new java.awt.Color(255, 255, 255));
        txtmaKhachhangTT.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblMaKhachHangTT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMaKhachHangTT.setText("Mã Khách Hàng");

        lblTenKHTT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTenKHTT.setText("Họ Tên");

        lblCMNDTT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCMNDTT.setText("CMND");

        txtCMNDTT.setEditable(false);
        txtCMNDTT.setBackground(new java.awt.Color(255, 255, 255));
        txtCMNDTT.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        txtTenKHTT.setEditable(false);
        txtTenKHTT.setBackground(new java.awt.Color(255, 255, 255));
        txtTenKHTT.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        txtSoDTTT.setEditable(false);
        txtSoDTTT.setBackground(new java.awt.Color(255, 255, 255));
        txtSoDTTT.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        txtEmailTT.setEditable(false);
        txtEmailTT.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailTT.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        lblEmailTT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmailTT.setText("Email");

        lblSoDTTT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSoDTTT.setText("Số ĐT");

        lblGioiTinhTT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGioiTinhTT.setText("Giới Tính");

        rdoNamTT.setBackground(new java.awt.Color(255, 255, 255));
        btgGioiTinhTT.add(rdoNamTT);
        rdoNamTT.setText("Nam");
        rdoNamTT.setEnabled(false);

        rdoNuTT.setBackground(new java.awt.Color(255, 255, 255));
        btgGioiTinhTT.add(rdoNuTT);
        rdoNuTT.setText("Nữ");
        rdoNuTT.setEnabled(false);

        javax.swing.GroupLayout PnlThongTinChuSoHuuLayout = new javax.swing.GroupLayout(PnlThongTinChuSoHuu);
        PnlThongTinChuSoHuu.setLayout(PnlThongTinChuSoHuuLayout);
        PnlThongTinChuSoHuuLayout.setHorizontalGroup(
            PnlThongTinChuSoHuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlThongTinChuSoHuuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlThongTinChuSoHuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlThongTinChuSoHuuLayout.createSequentialGroup()
                        .addComponent(lblMaKhachHangTT)
                        .addGap(22, 22, 22)
                        .addComponent(txtmaKhachhangTT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlThongTinChuSoHuuLayout.createSequentialGroup()
                        .addComponent(lblTenKHTT)
                        .addGap(80, 80, 80)
                        .addComponent(txtTenKHTT, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlThongTinChuSoHuuLayout.createSequentialGroup()
                        .addComponent(lblCMNDTT)
                        .addGap(87, 87, 87)
                        .addComponent(txtCMNDTT, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(PnlThongTinChuSoHuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlThongTinChuSoHuuLayout.createSequentialGroup()
                        .addComponent(lblGioiTinhTT)
                        .addGap(51, 51, 51)
                        .addComponent(rdoNamTT)
                        .addGap(35, 35, 35)
                        .addComponent(rdoNuTT))
                    .addGroup(PnlThongTinChuSoHuuLayout.createSequentialGroup()
                        .addComponent(lblSoDTTT)
                        .addGap(8, 8, 8)
                        .addComponent(txtSoDTTT, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlThongTinChuSoHuuLayout.createSequentialGroup()
                        .addComponent(lblEmailTT)
                        .addGap(14, 14, 14)
                        .addComponent(txtEmailTT, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        PnlThongTinChuSoHuuLayout.setVerticalGroup(
            PnlThongTinChuSoHuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlThongTinChuSoHuuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(PnlThongTinChuSoHuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaKhachHangTT)
                    .addComponent(txtmaKhachhangTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoDTTT)
                    .addComponent(txtSoDTTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(PnlThongTinChuSoHuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmailTT)
                    .addComponent(txtEmailTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenKHTT)
                    .addComponent(txtTenKHTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PnlThongTinChuSoHuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCMNDTT)
                    .addComponent(txtCMNDTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlThongTinChuSoHuuLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(PnlThongTinChuSoHuuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGioiTinhTT)
                            .addComponent(rdoNamTT)
                            .addComponent(rdoNuTT))))
                .addGap(52, 52, 52))
        );

        pnlMainTab.addTab("Thông Tin Chủ Sở Hữu", PnlThongTinChuSoHuu);

        pnlThongTinThanhVien.setBackground(new java.awt.Color(255, 255, 255));
        pnlThongTinThanhVien.setMaximumSize(new java.awt.Dimension(803, 260));
        pnlThongTinThanhVien.setMinimumSize(new java.awt.Dimension(803, 260));
        pnlThongTinThanhVien.setPreferredSize(new java.awt.Dimension(803, 260));
        pnlThongTinThanhVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTenKH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTenKH.setText("Họ Tên");
        pnlThongTinThanhVien.add(lblTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        lblCMND.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCMND.setText("CMND");
        pnlThongTinThanhVien.add(lblCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lblGioiTinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGioiTinh.setText("Giới Tính");
        pnlThongTinThanhVien.add(lblGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        lblSoDT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSoDT.setText("Số ĐT");
        pnlThongTinThanhVien.add(lblSoDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmail.setText("Email");
        pnlThongTinThanhVien.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        lblChuHo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblChuHo.setText("Chủ Hộ ");
        pnlThongTinThanhVien.add(lblChuHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, 20));

        txtTenKH.setEditable(false);
        txtTenKH.setBackground(new java.awt.Color(255, 255, 255));
        txtTenKH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        pnlThongTinThanhVien.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 252, -1));

        txtCMND.setEditable(false);
        txtCMND.setBackground(new java.awt.Color(255, 255, 255));
        txtCMND.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        pnlThongTinThanhVien.add(txtCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 252, -1));

        txtSoDT.setEditable(false);
        txtSoDT.setBackground(new java.awt.Color(255, 255, 255));
        txtSoDT.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        pnlThongTinThanhVien.add(txtSoDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 255, -1));

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        pnlThongTinThanhVien.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 255, -1));

        rdoNam.setBackground(new java.awt.Color(255, 255, 255));
        btgGioiTinh.add(rdoNam);
        rdoNam.setText("Nam");
        rdoNam.setEnabled(false);
        pnlThongTinThanhVien.add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        rdoNu.setBackground(new java.awt.Color(255, 255, 255));
        btgGioiTinh.add(rdoNu);
        rdoNu.setText("Nữ");
        rdoNu.setEnabled(false);
        pnlThongTinThanhVien.add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        cboCo.setBackground(new java.awt.Color(255, 255, 255));
        cboCo.setText(" ");
        cboCo.setEnabled(false);
        pnlThongTinThanhVien.add(cboCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, 20));

        lblMaKhachHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMaKhachHang.setText("Mã Khách Hàng");
        pnlThongTinThanhVien.add(lblMaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtmaKhachhang.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        pnlThongTinThanhVien.add(txtmaKhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 250, -1));

        lblXoa.setBackground(new java.awt.Color(255, 102, 102));
        lblXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblXoa.setForeground(new java.awt.Color(255, 255, 255));
        lblXoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Trash_25px.png"))); // NOI18N
        lblXoa.setText("Loại Bỏ");
        lblXoa.setOpaque(true);
        lblXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblXoaMousePressed(evt);
            }
        });
        pnlThongTinThanhVien.add(lblXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 100, 40));

        lblThem.setBackground(new java.awt.Color(153, 204, 0));
        lblThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblThem.setForeground(new java.awt.Color(255, 255, 255));
        lblThem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/New.png"))); // NOI18N
        lblThem.setText(" Thêm");
        lblThem.setOpaque(true);
        lblThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblThemMousePressed(evt);
            }
        });
        pnlThongTinThanhVien.add(lblThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 100, 40));

        pnlMainTab.addTab("Thông Tin Thành Viên", pnlThongTinThanhVien);

        pnlChuyenChuHo.setBackground(new java.awt.Color(255, 255, 255));
        pnlChuyenChuHo.setMaximumSize(new java.awt.Dimension(803, 260));
        pnlChuyenChuHo.setMinimumSize(new java.awt.Dimension(803, 260));

        lblTu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTu.setText("Từ");

        lblTenChuHo.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        lblTenChuHo.setForeground(new java.awt.Color(255, 0, 0));
        lblTenChuHo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblDen.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDen.setText("Đến");

        cboChuHoMoi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        lblChuyen.setBackground(new java.awt.Color(255, 153, 0));
        lblChuyen.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblChuyen.setForeground(new java.awt.Color(255, 255, 255));
        lblChuyen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Change_User_25px.png"))); // NOI18N
        lblChuyen.setText("Chuyển");
        lblChuyen.setOpaque(true);
        lblChuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblChuyenMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlChuyenChuHoLayout = new javax.swing.GroupLayout(pnlChuyenChuHo);
        pnlChuyenChuHo.setLayout(pnlChuyenChuHoLayout);
        pnlChuyenChuHoLayout.setHorizontalGroup(
            pnlChuyenChuHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChuyenChuHoLayout.createSequentialGroup()
                .addGroup(pnlChuyenChuHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChuyenChuHoLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(pnlChuyenChuHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlChuyenChuHoLayout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(lblDen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cboChuHoMoi, 0, 430, Short.MAX_VALUE)
                            .addComponent(lblTenChuHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlChuyenChuHoLayout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(lblChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
            .addGroup(pnlChuyenChuHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlChuyenChuHoLayout.createSequentialGroup()
                    .addGap(190, 376, Short.MAX_VALUE)
                    .addComponent(lblTu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 387, Short.MAX_VALUE)))
        );
        pnlChuyenChuHoLayout.setVerticalGroup(
            pnlChuyenChuHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChuyenChuHoLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(lblTenChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDen)
                .addGap(18, 18, 18)
                .addComponent(cboChuHoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(pnlChuyenChuHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlChuyenChuHoLayout.createSequentialGroup()
                    .addGap(0, 23, Short.MAX_VALUE)
                    .addComponent(lblTu)
                    .addGap(0, 217, Short.MAX_VALUE)))
        );

        pnlMainTab.addTab("Chuyển Chủ Hộ", pnlChuyenChuHo);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblChuyenTu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblChuyenTu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChuyenTu.setText("Chuyển Từ");

        lblChuSoHuuCu.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        lblChuSoHuuCu.setForeground(new java.awt.Color(255, 0, 0));
        lblChuSoHuuCu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblSang.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblSang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSang.setText("Sang");

        txtmaKHChuSoHuuMoi.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N

        lblMaKHChuSoHuuMoi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMaKHChuSoHuuMoi.setText("Mã Khách Hàng");

        lblChuyenChuSoHuu.setBackground(new java.awt.Color(255, 153, 0));
        lblChuyenChuSoHuu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblChuyenChuSoHuu.setForeground(new java.awt.Color(255, 255, 255));
        lblChuyenChuSoHuu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChuyenChuSoHuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Change_User_25px.png"))); // NOI18N
        lblChuyenChuSoHuu.setText("Chuyển");
        lblChuyenChuSoHuu.setOpaque(true);
        lblChuyenChuSoHuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblChuyenChuSoHuuMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblMaKHChuSoHuuMoi)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(txtmaKHChuSoHuuMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblChuyenTu, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(lblChuSoHuuCu, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblChuyenChuSoHuu, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblChuyenTu)
                .addGap(28, 28, 28)
                .addComponent(lblChuSoHuuCu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSang)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmaKHChuSoHuuMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaKHChuSoHuuMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChuyenChuSoHuu, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMainTab.addTab("Chuyển Chủ Sở Hữu", jPanel1);

        pnlMain.add(pnlMainTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 810, 290));

        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_TitlebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TitlebarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_lbl_TitlebarMouseDragged

    private void lbl_TitlebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_TitlebarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_lbl_TitlebarMousePressed

    private void jpn_MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_MinimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jpn_MinimizeMouseClicked

    private void jpn_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpn_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jpn_CloseMouseClicked

    private void tblKhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachhangMouseClicked
        index = tblKhachhang.getSelectedRow();
        this.edit_KH();
    }//GEN-LAST:event_tblKhachhangMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.load_KhachHang();
        this.load_ChuSoHuu();
    }//GEN-LAST:event_formWindowOpened

    private void lblThemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemMousePressed
        if (check()) {
            this.CheckNguoi(txtmaKhachhang.getText());
            this.loadThanhVien();
        }
        this.newmodel();
    }//GEN-LAST:event_lblThemMousePressed

    private void lblXoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXoaMousePressed
        this.loaibo();
        this.setTinhTrang();
        this.loadThanhVien();
        this.load_KhachHang();
        this.loadThanhVien();
        this.loadChuHo();
    }//GEN-LAST:event_lblXoaMousePressed

    private void lblChuyenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChuyenMousePressed
        this.chuyenChuHo();
        this.load_KhachHang();
        this.loadThanhVien();
        this.loadChuHo();
    }//GEN-LAST:event_lblChuyenMousePressed

    private void lblChuyenChuSoHuuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChuyenChuSoHuuMousePressed
        if (txtmaKHChuSoHuuMoi.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Không để trống mã khách hàng");
        } else {
            this.chuyenChuSoHuu();
            txtmaKHChuSoHuuMoi.setText("");
        }
    }//GEN-LAST:event_lblChuyenChuSoHuuMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinCanHoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinCanHoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinCanHoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinCanHoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinCanHoJFrame("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlThongTinChuSoHuu;
    private javax.swing.ButtonGroup btgGioiTinh;
    private javax.swing.ButtonGroup btgGioiTinhTT;
    private javax.swing.JComboBox<String> cboChuHoMoi;
    private javax.swing.JCheckBox cboCo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jpn_Close;
    private javax.swing.JLabel jpn_Minimize;
    private javax.swing.JLabel lblCMND;
    private javax.swing.JLabel lblCMNDTT;
    private javax.swing.JLabel lblChuHo;
    private javax.swing.JLabel lblChuSoHuuCu;
    private javax.swing.JLabel lblChuyen;
    private javax.swing.JLabel lblChuyenChuSoHuu;
    private javax.swing.JLabel lblChuyenTu;
    private javax.swing.JLabel lblDen;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailTT;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblGioiTinhTT;
    private javax.swing.JLabel lblMaKHChuSoHuuMoi;
    private javax.swing.JLabel lblMaKhachHang;
    private javax.swing.JLabel lblMaKhachHangTT;
    private javax.swing.JLabel lblSang;
    private javax.swing.JLabel lblSoDT;
    private javax.swing.JLabel lblSoDTTT;
    private javax.swing.JLabel lblTenChuHo;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblTenKHTT;
    private javax.swing.JLabel lblThem;
    private javax.swing.JLabel lblTu;
    private javax.swing.JLabel lblXoa;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JLabel lbl_Titlebar;
    private javax.swing.JPanel pnlChuyenChuHo;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTabbedPane pnlMainTab;
    private javax.swing.JPanel pnlThongTinThanhVien;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNamTT;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoNuTT;
    private javax.swing.JScrollPane sclKhachhang;
    private javax.swing.JTable tblKhachhang;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtCMNDTT;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailTT;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtSoDTTT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenKHTT;
    private javax.swing.JTextField txtmaKHChuSoHuuMoi;
    private javax.swing.JTextField txtmaKhachhang;
    private javax.swing.JTextField txtmaKhachhangTT;
    // End of variables declaration//GEN-END:variables

    ThongTinKhachHangDAO khachHangDAO = new ThongTinKhachHangDAO();
    int index = 0;

    void load_ChuSoHuu() {
        try {
            ThongTinKhachHang model = khachHangDAO.selectChuHo(canhoID);
            if (model != null) {
                this.setModelChuSoHuu(model);
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }

    void setModelChuSoHuu(ThongTinKhachHang model) {
        txtmaKhachhangTT.setText(model.getKhachHangid());
        txtTenKHTT.setText(model.getTenKhachHang());
        lblChuSoHuuCu.setText(model.getTenKhachHang());
        txtCMNDTT.setText(model.getCMND());
        txtSoDTTT.setText(model.getSodt());
        txtEmailTT.setText(model.getEmail());
        if (model.getGioiTinh()) {
            rdoNamTT.setSelected(true);
        } else {
            rdoNuTT.setSelected(true);
        }
    }

    void loadChuHo() {
        try {
            ResultSet rs = JDBC.executeQuery(" SELECT TenKhachHang FROM dbo.ThongTinKhachHang   WHERE CanHoId = ? AND ChuHo=1 ", canhoID);
            if (rs.next()) {
                String Ten = rs.getString(1);
                lblTenChuHo.setText(Ten);
            }
        } catch (SQLException e) {
        }
    }

    void loadThanhVien() {
        ResultSet rs = JDBC.executeQuery("SELECT TenKhachHang FROM dbo.ThongTinKhachHang   WHERE CanHoId = ? AND ChuHo=0", canhoID);
        try {
            cboChuHoMoi.removeAllItems();
            while (rs.next()) {
                cboChuHoMoi.addItem(rs.getString(1));
            }
            cboChuHoMoi.setSelectedItem(1);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    void load_KhachHang() {
        DefaultTableModel model = (DefaultTableModel) tblKhachhang.getModel();
        model.setRowCount(0);
        try {
            List<ThongTinKhachHang> list_SP = khachHangDAO.selectByIdCH(canhoID);
            for (ThongTinKhachHang KhachHang : list_SP) {
                Object[] row = {
                    KhachHang.getKhachHangid(),
                    KhachHang.getTenKhachHang(),
                    KhachHang.getCMND(),
                    KhachHang.getGioiTinh() ? "Nam" : "Nữ",
                    KhachHang.getSodt(),
                    KhachHang.getEmail(),
                    KhachHang.isChuHo() ? "X" : "",};
                model.addRow(row);
            }
        } catch (ExceptionInInitializerError e) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu !");
            System.err.println(e);
        }
    }

    void setModel_KH(ThongTinKhachHang model) {
        txtmaKhachhang.setText(model.getKhachHangid());
        txtTenKH.setText(model.getTenKhachHang());
        txtCMND.setText(model.getCMND());
        txtSoDT.setText(model.getSodt());
        txtEmail.setText(model.getEmail());
        if (model.getGioiTinh()) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        if (model.isChuHo()) {
            cboCo.setSelected(true);
        } else {
            cboCo.setSelected(false);
        }
    }

    ThongTinKhachHang getModel_KH() {
        ThongTinKhachHang model = new ThongTinKhachHang();
        model.setKhachHangid(txtmaKhachhang.getText());
        model.setCanHoid(canhoID);
        return model;
    }

    void edit_KH() {
        try {
            String makh = (String) tblKhachhang.getValueAt(index, 0);
            ThongTinKhachHang model = khachHangDAO.selectByIdKH(makh);
            if (model != null) {
                this.setModel_KH(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu!");
            System.err.println(e);
        }
    }

    void them() {
        ThongTinKhachHang model = getModel_KH();
        try {
            khachHangDAO.updateCanHo(model);
            khachHangDAO.updateCanHoTinhTrangO(model);
            this.load_KhachHang();
        } catch (Exception e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(this, "Thêm khách hàng vào căn hộ thất bại!");
        }
    }

    private boolean check() {
        if (txtmaKhachhang.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Không để trống mã khách hàng!");
            return false;
        }
        return true;
    }

    void CheckNguoi(String MaKH) {
        try {
            ResultSet rs = JDBC.executeQuery(" SELECT KhachHangId,CanHoId FROM dbo.ThongTinKhachHang WHERE KhachHangId = ?", MaKH);
            if (rs.next()) {
                String KHID = rs.getString(1);
                String CHID = rs.getString(2);
                if (CHID == null) {
                    if (txtmaKhachhang.getText().equals(KHID)) {
                        this.them();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Khách hàng này đang là thành viên của căn hộ khác!");
                    newmodel();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không tồn tại khách hàng này!");
                newmodel();
            }
        } catch (SQLException e) {
            System.err.println(e);
        }
    }

    void chuyenChuHo() {
        try {
            khachHangDAO.updateChuHo(lblTenChuHo.getText(), (String) cboChuHoMoi.getSelectedItem(), canhoID);
            JOptionPane.showMessageDialog(this, "Chuyển chủ hộ thành công");
        } catch (Exception e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(this, "Chuyển chủ hộ thất bại");
        }
    }

    void newmodel() {
        txtCMND.setText("");
        txtEmail.setText("");
        txtSoDT.setText("");
        txtTenKH.setText("");
        txtmaKhachhang.setText("");
        rdoNam.setSelected(true);
    }

    void loaibo() {
        try {
            int Traloi = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa thành viên này không ?", "Thông Báo", JOptionPane.YES_NO_OPTION);
            if (Traloi == 0) {
                khachHangDAO.updateLoaiBo(txtmaKhachhang.getText());
                JOptionPane.showMessageDialog(this, "Đã loại bỏ thành viên ra khỏi căn hộ");
                this.load_KhachHang();
                newmodel();
            } else {
                newmodel();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loại bỏ thành viên thất bại");
            System.err.println(e);
            newmodel();
        }
    }

    void setTinhTrang() {
        ThongTinKhachHang model = getModel_KH();
        int SoNguoi = 0;
        ResultSet rs = JDBC.executeQuery("SELECT COUNT(KhachHangId) FROM dbo.ThongTinKhachHang WHERE CanHoId =?", canhoID);
        try {
            if (rs.next()) {
                SoNguoi = rs.getInt(1);
            }
            if (SoNguoi == 0) {
                khachHangDAO.updateCanHoTinhTrangTrong(model);
            }
        } catch (Exception e) {
        }
    }

    void chuyenChuSoHuu() {
        ResultSet rs = JDBC.executeQuery("SELECT KhachHangId FROM dbo.ThongTinKhachHang WHERE KhachHangId = ?", txtmaKHChuSoHuuMoi.getText());
        try {
            if (rs.next()) {
                int Traloi = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn chuyển quyền sở hữu căn hộ này ?", "Thông Báo", JOptionPane.YES_NO_OPTION);
                if (Traloi == 0) {
                    khachHangDAO.updateChuSoHuu(txtmaKHChuSoHuuMoi.getText(), canhoID);
                    JOptionPane.showMessageDialog(this, "Chuyển dao sở hữu thành công");
                    this.load_ChuSoHuu();
                } else {
                    this.load_ChuSoHuu();
                }

            } else {
                JOptionPane.showMessageDialog(this, "Không tồn tại khách hàng này");
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}
