/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duan.UI;

/**
 *
 * @author anhdu
 */
public class TrangChuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TranChuJPanel
     */
    public TrangChuJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_SoPhongDangQuanLy = new javax.swing.JPanel();
        lbl_IconHome = new javax.swing.JLabel();
        lbl_TongSoCanHo = new javax.swing.JLabel();
        lbl_IconCanHo = new javax.swing.JLabel();
        pnl_SoNhanKhau = new javax.swing.JPanel();
        lbl_IconBike = new javax.swing.JLabel();
        lbl_IconPhuongTien = new javax.swing.JLabel();
        lbl_TongSoPhuongTien = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1040, 660));
        setMinimumSize(new java.awt.Dimension(1040, 660));
        setPreferredSize(new java.awt.Dimension(1040, 660));

        pnl_SoPhongDangQuanLy.setBackground(new java.awt.Color(255, 85, 85));
        pnl_SoPhongDangQuanLy.setMaximumSize(new java.awt.Dimension(330, 230));
        pnl_SoPhongDangQuanLy.setMinimumSize(new java.awt.Dimension(330, 230));

        lbl_IconHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Home.png"))); // NOI18N

        lbl_TongSoCanHo.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lbl_TongSoCanHo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TongSoCanHo.setText("100");

        lbl_IconCanHo.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lbl_IconCanHo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_IconCanHo.setText("Căn Hộ");

        javax.swing.GroupLayout pnl_SoPhongDangQuanLyLayout = new javax.swing.GroupLayout(pnl_SoPhongDangQuanLy);
        pnl_SoPhongDangQuanLy.setLayout(pnl_SoPhongDangQuanLyLayout);
        pnl_SoPhongDangQuanLyLayout.setHorizontalGroup(
            pnl_SoPhongDangQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SoPhongDangQuanLyLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_IconHome)
                .addGroup(pnl_SoPhongDangQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_SoPhongDangQuanLyLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lbl_TongSoCanHo))
                    .addGroup(pnl_SoPhongDangQuanLyLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lbl_IconCanHo)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pnl_SoPhongDangQuanLyLayout.setVerticalGroup(
            pnl_SoPhongDangQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SoPhongDangQuanLyLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lbl_TongSoCanHo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(lbl_IconCanHo)
                .addGap(43, 43, 43))
            .addGroup(pnl_SoPhongDangQuanLyLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lbl_IconHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_SoNhanKhau.setBackground(new java.awt.Color(121, 196, 71));
        pnl_SoNhanKhau.setMaximumSize(new java.awt.Dimension(330, 230));
        pnl_SoNhanKhau.setMinimumSize(new java.awt.Dimension(330, 230));

        lbl_IconBike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/duan/Logo/Motorcycle.png"))); // NOI18N

        lbl_IconPhuongTien.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lbl_IconPhuongTien.setForeground(new java.awt.Color(255, 255, 255));
        lbl_IconPhuongTien.setText("Phương Tiện");

        lbl_TongSoPhuongTien.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lbl_TongSoPhuongTien.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TongSoPhuongTien.setText("100");

        javax.swing.GroupLayout pnl_SoNhanKhauLayout = new javax.swing.GroupLayout(pnl_SoNhanKhau);
        pnl_SoNhanKhau.setLayout(pnl_SoNhanKhauLayout);
        pnl_SoNhanKhauLayout.setHorizontalGroup(
            pnl_SoNhanKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SoNhanKhauLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_IconBike)
                .addGroup(pnl_SoNhanKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_SoNhanKhauLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lbl_TongSoPhuongTien))
                    .addGroup(pnl_SoNhanKhauLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_IconPhuongTien)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnl_SoNhanKhauLayout.setVerticalGroup(
            pnl_SoNhanKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SoNhanKhauLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lbl_TongSoPhuongTien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_IconPhuongTien)
                .addGap(43, 43, 43))
            .addGroup(pnl_SoNhanKhauLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lbl_IconBike)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(pnl_SoPhongDangQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(pnl_SoNhanKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_SoNhanKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_SoPhongDangQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_IconBike;
    private javax.swing.JLabel lbl_IconCanHo;
    private javax.swing.JLabel lbl_IconHome;
    private javax.swing.JLabel lbl_IconPhuongTien;
    private javax.swing.JLabel lbl_TongSoCanHo;
    private javax.swing.JLabel lbl_TongSoPhuongTien;
    private javax.swing.JPanel pnl_SoNhanKhau;
    private javax.swing.JPanel pnl_SoPhongDangQuanLy;
    // End of variables declaration//GEN-END:variables
}
